site_name: Ilha Primeira - Documentação
site_url: https://<SEU_USUARIO>.github.io/<SEU_REPOSITORIO>  # Altere isso!
repo_url: https://github.com/<SEU_USUARIO>/<SEU_REPOSITORIO>
repo_name: GitHub

theme:
  name: material
  language: pt-BR
  palette:
    scheme: default
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate

nav:
  - Início: index.md
  - Documentação:
      - Brainstorm: docs/brainstorm.md
      - 5W2H: docs/5w2h.md
      - Requisitos: docs/requisitos.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tabbed
